_includes/_companies.html

Update Cookpad Indonesia description

---

_includes/_companies.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/id-ruby/id-ruby/5)

Update cpxi description

---

_includes/_companies.html

Alphabetical order and use double quotes on HTML

---

.gitignore
_includes/_companies.html

Update dari management terkait info URL dan company information

Updating CPXI info and URL reference

---

_includes/_companies.html

Apparently companies should be in alphabetical order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/id-ruby/id-ruby/14)

Fix companies order

---

twitter/index.html

fix twitter redirect

---

conf/2017/index.html

Fix Code of Conduct Toggle

---

conf/2017/index.html

Thanks to duration reduction, we now can accomodate 10 talks, increased from 8 talks.
Also, I think we should not make the "talks" box smaller than "lightning talks", since actually they have longer duration and bigger presence

update to 10 talks

---

conf/2017/index.html

Since Gojek venue has limited capacity

reduce target attendees from 300 to 200

---

_data/companies.yml

Hi, I make this PR to change Quipper link from  Quipper School to Quipper Video landing page, as requested by our Product Manager, thanks 🙏

update Quipper url to Quipper video landing page

---

_assets/stylesheets/conf.scss
conf/2017/index.html

Fix mobile view for sponsors

---

_assets/stylesheets/conf.scss
conf/2017/index.html

Add ticket button for registration

Add ticket button

---

_assets/stylesheets/conf.scss
_data/conf/keynote_speakers.yml
_data/conf/speakers.yml
conf/2017/index.html

A quick updates of talk titles and speakers.

Put up list of speakers and talks

---

conf/2017/index.html

Thank you very much for submitters!

Call for paper has ended 🎉

---

_layouts/conf.html
conf/2017/index.html

This PR adds minimum metadata for crawlers to pick up when we share the page.

Fix conf page meta data for better sharing

---

_data/conf/speakers.yml

Update LT Speakers

---

_assets/stylesheets/conf.scss
conf/2017/index.html

Add paypal button for international buyer

paypal button

---

_config.yml
_includes/_footer.html
_layouts/base.html

this pull request consist:
1. update meetup button to our next meetup (Jan 2019)
2. add the capability of the button to hide their self after the day of the meetup
3. add id-ruby telegram group link
Thanks

Update meetup button and add telegram group link

---

_config.yml
cfp/index.html
conf/2019/index.html

Update RubyConf 2019 CFP

---

conf/2019/index.html

Its September 29, 2019. (Sunday)

Update Conf date

---

_assets/stylesheets/conf.scss
conf/2019/index.html

Notable changes:
- Venue
- The rest is shown with "coming soon"

Update RubyconfID 2019 information

---

_data/jobs.yml

Add Quipper Job at https://career.quipper.com/id/jobs/web-engineer

quipper job

---

_data/jobs.yml

This PR according our partnership with Kalibrr.
Thanks :tada:

Update monthly career oppurtunities (partnership with Kalibrr)

---

conf/2019/index.html
ticket-student/index.html
ticket/index.html

Add ticket link

---

_data/conf_2019/keynote_speakers.yml
conf/2019/index.html

Update Ryan's talk and add speakers URL

---

_data/conf_2019/community_partners.yml
_data/conf_2019/media_partners.yml
_data/conf_2019/other_sponsors.yml
conf/2019/index.html

Adds miscellaneous sponsors and partners

---

_assets/stylesheets/conf.scss
_data/conf_2019/community_partners.yml
_data/conf_2019/keynote_speakers.yml
_data/conf_2019/media_partners.yml
_data/conf_2019/speakers.yml
conf/2019/index.html

Update speakers and small CSS tweaks

---

_assets/stylesheets/conf.scss
_data/conf_2019/speakers.yml
conf/2019/index.html

Update Speakers and Tweak Mobile Design

---

_data/conf_2019/keynote_speakers.yml
_data/conf_2019/speakers.yml
conf/2019/index.html

This PR closes #109, closes #110, closes #111, and closes #112

Update speakers and keynote speaker

---

_data/conf_2019/speakers.yml

Closes https://github.com/id-ruby/id-ruby/issues/116 and closes https://github.com/id-ruby/id-ruby/issues/114

Update speaker photos

---

.github/workflows/deploy.yml

Add GitHub action to deploy upon push to master branch.

Add workflow for deployment

---

.github/workflows/deploy.yml
Rakefile

Update GitHub Action to use `rake` to deploy to GitHub Pages

Deploy using rake

---

conf/2019/guide/index.html

Thanks to @rikarumi & @waruboy 👍

Add conference guide
